use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'SNAugusPopView_Example' do
  pod 'SNAugusPopView', :path => '../'

  target 'SNAugusPopView_Tests' do
    inherit! :search_paths

    
  end
end
